- hosts: localhost 192.168.49.2
  become: true
  tasks:
    - name: Deploy new pod
      command: kubectl apply -f deployement.yaml --validation=false

    - name: Deploy new service
      command: kubectl apply -f service.yaml
